  Vagrant.configure("2") do |config|
    config.vm.box = "peru/ubuntu-20.04-desktop-amd64"
    config.vm.box_version = "20210315.01"

    config.vm.provider :virtualbox do |v|
      v.gui = true
      v.memory = 2048
    end
  
    # Currently "ubuntu/bionic64" on VirtualBox requires `type: "virtualbox"`
    # to make synced folder works.
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  
    # Add Google Chrome repository
    config.vm.provision :shell, inline: "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub|sudo apt-key add -"
    config.vm.provision :shell, inline: "sudo sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" > /etc/apt/sources.list.d/google.list'"
  
    # Update repositories
    config.vm.provision :shell, inline: "sudo apt update -y"
  
    # Upgrade installed packages
    config.vm.provision :shell, inline: "sudo apt upgrade -y"
  
    # Add `vagrant` to Administrator
    config.vm.provision :shell, inline: "sudo usermod -a -G sudo vagrant"

    # Install needed stuff
    config.vm.provision :shell, inline: "sudo apt install -y git curl vim zsh mtr apt-transport-https ca-certificates gnupg-agent software-properties-common fonts-powerline" 

    # Download repo
    config.vm.provision :shell, inline: "git clone https://github.com/stefanfluit/bitwarden-hetzner.git /home/vagrant/bitwarden-hetzner"
    config.vm.provision :shell, inline: "sudo chown vagrant:vagrant -R /home/vagrant/bitwarden-hetzner"

    # Configure ZSH
    config.vm.provision :shell, inline: "wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh"
    config.vm.provision :shell, inline: "sudo cp -r /root/.oh-my-zsh /home/vagrant/.oh-my-zsh"
    config.vm.provision :shell, inline: "wget -O /home/vagrant/.zshrc https://raw.githubusercontent.com/stefanfluit/default_files/master/oh_my_zsh/.zshrc_vagrant"
    config.vm.provision :shell, inline: "sudo chsh -s $(which zsh) vagrant"

  end